apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: mynewapp

build:
  artifacts:
  - image: myusername-mynewapp
    custom:
      buildCommand: clj -X:skaffold-dev
      dependencies:
        paths:
        - src/
        - dev/
    sync:
      manual:
      - src: src/**
        dest: .
      - src: dev/**
        dest: .
      - src: resources/**
        dest: .

deploy:
  kubectl:
    manifests:
    - deployment.yaml

portForward:
- resourceType: service
  resourceName: myusername-mynewapp
  port: 8080
- resourceType: service
  resourceName: myusername-mynewapp
  port: 3177
